// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: models/game_model.proto

package models

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Color int32

const (
	Color_BLACK Color = 0
	Color_WHITE Color = 1
)

// Enum value maps for Color.
var (
	Color_name = map[int32]string{
		0: "BLACK",
		1: "WHITE",
	}
	Color_value = map[string]int32{
		"BLACK": 0,
		"WHITE": 1,
	}
)

func (x Color) Enum() *Color {
	p := new(Color)
	*p = x
	return p
}

func (x Color) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Color) Descriptor() protoreflect.EnumDescriptor {
	return file_models_game_model_proto_enumTypes[0].Descriptor()
}

func (Color) Type() protoreflect.EnumType {
	return &file_models_game_model_proto_enumTypes[0]
}

func (x Color) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Color.Descriptor instead.
func (Color) EnumDescriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{0}
}

type Rules int32

const (
	Rules_JAPANESE Rules = 0
	Rules_CHINESE  Rules = 1
)

// Enum value maps for Rules.
var (
	Rules_name = map[int32]string{
		0: "JAPANESE",
		1: "CHINESE",
	}
	Rules_value = map[string]int32{
		"JAPANESE": 0,
		"CHINESE":  1,
	}
)

func (x Rules) Enum() *Rules {
	p := new(Rules)
	*p = x
	return p
}

func (x Rules) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Rules) Descriptor() protoreflect.EnumDescriptor {
	return file_models_game_model_proto_enumTypes[1].Descriptor()
}

func (Rules) Type() protoreflect.EnumType {
	return &file_models_game_model_proto_enumTypes[1]
}

func (x Rules) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Rules.Descriptor instead.
func (Rules) EnumDescriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{1}
}

type GameSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	BoardSize     int32                  `protobuf:"varint,2,opt,name=board_size,json=boardSize,proto3" json:"board_size,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Komi          float32                `protobuf:"fixed32,4,opt,name=komi,proto3" json:"komi,omitempty"`
	Date          string                 `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	IsFinished    bool                   `protobuf:"varint,6,opt,name=is_finished,json=isFinished,proto3" json:"is_finished,omitempty"`
	Rules         Rules                  `protobuf:"varint,7,opt,name=rules,proto3,enum=tesuji.models.v1.Rules" json:"rules,omitempty"`
	BlackPlayer   *Player                `protobuf:"bytes,8,opt,name=black_player,json=blackPlayer,proto3" json:"black_player,omitempty"`
	WhitePlayer   *Player                `protobuf:"bytes,9,opt,name=white_player,json=whitePlayer,proto3" json:"white_player,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameSummary) Reset() {
	*x = GameSummary{}
	mi := &file_models_game_model_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameSummary) ProtoMessage() {}

func (x *GameSummary) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameSummary.ProtoReflect.Descriptor instead.
func (*GameSummary) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{0}
}

func (x *GameSummary) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GameSummary) GetBoardSize() int32 {
	if x != nil {
		return x.BoardSize
	}
	return 0
}

func (x *GameSummary) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GameSummary) GetKomi() float32 {
	if x != nil {
		return x.Komi
	}
	return 0
}

func (x *GameSummary) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GameSummary) GetIsFinished() bool {
	if x != nil {
		return x.IsFinished
	}
	return false
}

func (x *GameSummary) GetRules() Rules {
	if x != nil {
		return x.Rules
	}
	return Rules_JAPANESE
}

func (x *GameSummary) GetBlackPlayer() *Player {
	if x != nil {
		return x.BlackPlayer
	}
	return nil
}

func (x *GameSummary) GetWhitePlayer() *Player {
	if x != nil {
		return x.WhitePlayer
	}
	return nil
}

type Game struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *GameSummary           `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	GameData      []*GameState           `protobuf:"bytes,2,rep,name=game_data,json=gameData,proto3" json:"game_data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Game) Reset() {
	*x = Game{}
	mi := &file_models_game_model_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Game) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Game) ProtoMessage() {}

func (x *Game) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Game.ProtoReflect.Descriptor instead.
func (*Game) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{1}
}

func (x *Game) GetSummary() *GameSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *Game) GetGameData() []*GameState {
	if x != nil {
		return x.GameData
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rank          int32                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_models_game_model_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{2}
}

func (x *Player) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Player) GetRank() int32 {
	if x != nil {
		return x.Rank
	}
	return 0
}

type GameState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastMove      *Move                  `protobuf:"bytes,1,opt,name=last_move,json=lastMove,proto3" json:"last_move,omitempty"`
	Position      *Position              `protobuf:"bytes,2,opt,name=position,proto3" json:"position,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameState) Reset() {
	*x = GameState{}
	mi := &file_models_game_model_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameState) ProtoMessage() {}

func (x *GameState) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameState.ProtoReflect.Descriptor instead.
func (*GameState) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{3}
}

func (x *GameState) GetLastMove() *Move {
	if x != nil {
		return x.LastMove
	}
	return nil
}

func (x *GameState) GetPosition() *Position {
	if x != nil {
		return x.Position
	}
	return nil
}

type Position struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []int32                `protobuf:"varint,1,rep,packed,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Position) Reset() {
	*x = Position{}
	mi := &file_models_game_model_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Position) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Position) ProtoMessage() {}

func (x *Position) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Position.ProtoReflect.Descriptor instead.
func (*Position) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{4}
}

func (x *Position) GetData() []int32 {
	if x != nil {
		return x.Data
	}
	return nil
}

type Move struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Point         *Point                 `protobuf:"bytes,1,opt,name=point,proto3" json:"point,omitempty"`
	IsPass        bool                   `protobuf:"varint,2,opt,name=is_pass,json=isPass,proto3" json:"is_pass,omitempty"`
	Color         Color                  `protobuf:"varint,3,opt,name=color,proto3,enum=tesuji.models.v1.Color" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Move) Reset() {
	*x = Move{}
	mi := &file_models_game_model_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Move) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Move) ProtoMessage() {}

func (x *Move) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Move.ProtoReflect.Descriptor instead.
func (*Move) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{5}
}

func (x *Move) GetPoint() *Point {
	if x != nil {
		return x.Point
	}
	return nil
}

func (x *Move) GetIsPass() bool {
	if x != nil {
		return x.IsPass
	}
	return false
}

func (x *Move) GetColor() Color {
	if x != nil {
		return x.Color
	}
	return Color_BLACK
}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_models_game_model_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_models_game_model_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_models_game_model_proto_rawDescGZIP(), []int{6}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_models_game_model_proto protoreflect.FileDescriptor

const file_models_game_model_proto_rawDesc = "" +
	"\n" +
	"\x17models/game_model.proto\x12\x10tesuji.models.v1\"\xc4\x02\n" +
	"\vGameSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"board_size\x18\x02 \x01(\x05R\tboardSize\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x12\n" +
	"\x04komi\x18\x04 \x01(\x02R\x04komi\x12\x12\n" +
	"\x04date\x18\x05 \x01(\tR\x04date\x12\x1f\n" +
	"\vis_finished\x18\x06 \x01(\bR\n" +
	"isFinished\x12-\n" +
	"\x05rules\x18\a \x01(\x0e2\x17.tesuji.models.v1.RulesR\x05rules\x12;\n" +
	"\fblack_player\x18\b \x01(\v2\x18.tesuji.models.v1.PlayerR\vblackPlayer\x12;\n" +
	"\fwhite_player\x18\t \x01(\v2\x18.tesuji.models.v1.PlayerR\vwhitePlayer\"y\n" +
	"\x04Game\x127\n" +
	"\asummary\x18\x01 \x01(\v2\x1d.tesuji.models.v1.GameSummaryR\asummary\x128\n" +
	"\tgame_data\x18\x02 \x03(\v2\x1b.tesuji.models.v1.GameStateR\bgameData\"0\n" +
	"\x06Player\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x05R\x04rank\"x\n" +
	"\tGameState\x123\n" +
	"\tlast_move\x18\x01 \x01(\v2\x16.tesuji.models.v1.MoveR\blastMove\x126\n" +
	"\bposition\x18\x02 \x01(\v2\x1a.tesuji.models.v1.PositionR\bposition\"\"\n" +
	"\bPosition\x12\x16\n" +
	"\x04data\x18\x01 \x03(\x05B\x02\x10\x01R\x04data\"}\n" +
	"\x04Move\x12-\n" +
	"\x05point\x18\x01 \x01(\v2\x17.tesuji.models.v1.PointR\x05point\x12\x17\n" +
	"\ais_pass\x18\x02 \x01(\bR\x06isPass\x12-\n" +
	"\x05color\x18\x03 \x01(\x0e2\x17.tesuji.models.v1.ColorR\x05color\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y*\x1d\n" +
	"\x05Color\x12\t\n" +
	"\x05BLACK\x10\x00\x12\t\n" +
	"\x05WHITE\x10\x01*\"\n" +
	"\x05Rules\x12\f\n" +
	"\bJAPANESE\x10\x00\x12\v\n" +
	"\aCHINESE\x10\x01B0Z.github.com/J0hnLenin/Tesuji/internal/pb/modelsb\x06proto3"

var (
	file_models_game_model_proto_rawDescOnce sync.Once
	file_models_game_model_proto_rawDescData []byte
)

func file_models_game_model_proto_rawDescGZIP() []byte {
	file_models_game_model_proto_rawDescOnce.Do(func() {
		file_models_game_model_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_models_game_model_proto_rawDesc), len(file_models_game_model_proto_rawDesc)))
	})
	return file_models_game_model_proto_rawDescData
}

var file_models_game_model_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_models_game_model_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_models_game_model_proto_goTypes = []any{
	(Color)(0),          // 0: tesuji.models.v1.Color
	(Rules)(0),          // 1: tesuji.models.v1.Rules
	(*GameSummary)(nil), // 2: tesuji.models.v1.GameSummary
	(*Game)(nil),        // 3: tesuji.models.v1.Game
	(*Player)(nil),      // 4: tesuji.models.v1.Player
	(*GameState)(nil),   // 5: tesuji.models.v1.GameState
	(*Position)(nil),    // 6: tesuji.models.v1.Position
	(*Move)(nil),        // 7: tesuji.models.v1.Move
	(*Point)(nil),       // 8: tesuji.models.v1.Point
}
var file_models_game_model_proto_depIdxs = []int32{
	1, // 0: tesuji.models.v1.GameSummary.rules:type_name -> tesuji.models.v1.Rules
	4, // 1: tesuji.models.v1.GameSummary.black_player:type_name -> tesuji.models.v1.Player
	4, // 2: tesuji.models.v1.GameSummary.white_player:type_name -> tesuji.models.v1.Player
	2, // 3: tesuji.models.v1.Game.summary:type_name -> tesuji.models.v1.GameSummary
	5, // 4: tesuji.models.v1.Game.game_data:type_name -> tesuji.models.v1.GameState
	7, // 5: tesuji.models.v1.GameState.last_move:type_name -> tesuji.models.v1.Move
	6, // 6: tesuji.models.v1.GameState.position:type_name -> tesuji.models.v1.Position
	8, // 7: tesuji.models.v1.Move.point:type_name -> tesuji.models.v1.Point
	0, // 8: tesuji.models.v1.Move.color:type_name -> tesuji.models.v1.Color
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_models_game_model_proto_init() }
func file_models_game_model_proto_init() {
	if File_models_game_model_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_models_game_model_proto_rawDesc), len(file_models_game_model_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_game_model_proto_goTypes,
		DependencyIndexes: file_models_game_model_proto_depIdxs,
		EnumInfos:         file_models_game_model_proto_enumTypes,
		MessageInfos:      file_models_game_model_proto_msgTypes,
	}.Build()
	File_models_game_model_proto = out.File
	file_models_game_model_proto_goTypes = nil
	file_models_game_model_proto_depIdxs = nil
}
