// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: games_api/games.proto

package games_api

import (
	models "github.com/J0hnLenin/Tesuji/internal/pb/models"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetGamesSummaryListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int64                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int64                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesSummaryListRequest) Reset() {
	*x = GetGamesSummaryListRequest{}
	mi := &file_games_api_games_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesSummaryListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesSummaryListRequest) ProtoMessage() {}

func (x *GetGamesSummaryListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_games_api_games_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesSummaryListRequest.ProtoReflect.Descriptor instead.
func (*GetGamesSummaryListRequest) Descriptor() ([]byte, []int) {
	return file_games_api_games_proto_rawDescGZIP(), []int{0}
}

func (x *GetGamesSummaryListRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGamesSummaryListRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetGamesSummaryListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Games         []*models.GameSummary  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGamesSummaryListResponse) Reset() {
	*x = GetGamesSummaryListResponse{}
	mi := &file_games_api_games_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGamesSummaryListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGamesSummaryListResponse) ProtoMessage() {}

func (x *GetGamesSummaryListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_games_api_games_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGamesSummaryListResponse.ProtoReflect.Descriptor instead.
func (*GetGamesSummaryListResponse) Descriptor() ([]byte, []int) {
	return file_games_api_games_proto_rawDescGZIP(), []int{1}
}

func (x *GetGamesSummaryListResponse) GetGames() []*models.GameSummary {
	if x != nil {
		return x.Games
	}
	return nil
}

type GetGameByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDRequest) Reset() {
	*x = GetGameByIDRequest{}
	mi := &file_games_api_games_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDRequest) ProtoMessage() {}

func (x *GetGameByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_games_api_games_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDRequest.ProtoReflect.Descriptor instead.
func (*GetGameByIDRequest) Descriptor() ([]byte, []int) {
	return file_games_api_games_proto_rawDescGZIP(), []int{2}
}

func (x *GetGameByIDRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetGameByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Game          *models.Game           `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGameByIDResponse) Reset() {
	*x = GetGameByIDResponse{}
	mi := &file_games_api_games_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGameByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGameByIDResponse) ProtoMessage() {}

func (x *GetGameByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_games_api_games_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGameByIDResponse.ProtoReflect.Descriptor instead.
func (*GetGameByIDResponse) Descriptor() ([]byte, []int) {
	return file_games_api_games_proto_rawDescGZIP(), []int{3}
}

func (x *GetGameByIDResponse) GetGame() *models.Game {
	if x != nil {
		return x.Game
	}
	return nil
}

var File_games_api_games_proto protoreflect.FileDescriptor

const file_games_api_games_proto_rawDesc = "" +
	"\n" +
	"\x15games_api/games.proto\x12\x11tesuji.service.v1\x1a\x17models/game_model.proto\x1a\x1cgoogle/api/annotations.proto\"F\n" +
	"\x1aGetGamesSummaryListRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x03R\x04page\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x03R\x05limit\"R\n" +
	"\x1bGetGamesSummaryListResponse\x123\n" +
	"\x05games\x18\x01 \x03(\v2\x1d.tesuji.models.v1.GameSummaryR\x05games\"$\n" +
	"\x12GetGameByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"A\n" +
	"\x13GetGameByIDResponse\x12*\n" +
	"\x04game\x18\x01 \x01(\v2\x16.tesuji.models.v1.GameR\x04game2\x96\x02\n" +
	"\fGamesService\x12\x8b\x01\n" +
	"\x13GetGamesSummaryList\x12-.tesuji.service.v1.GetGamesSummaryListRequest\x1a..tesuji.service.v1.GetGamesSummaryListResponse\"\x15\x82\xd3\xe4\x93\x02\x0f\x12\r/api/v1/games\x12x\n" +
	"\vGetGameByID\x12%.tesuji.service.v1.GetGameByIDRequest\x1a&.tesuji.service.v1.GetGameByIDResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/games/{id}B3Z1github.com/J0hnLenin/Tesuji/internal/pb/games_apib\x06proto3"

var (
	file_games_api_games_proto_rawDescOnce sync.Once
	file_games_api_games_proto_rawDescData []byte
)

func file_games_api_games_proto_rawDescGZIP() []byte {
	file_games_api_games_proto_rawDescOnce.Do(func() {
		file_games_api_games_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_games_api_games_proto_rawDesc), len(file_games_api_games_proto_rawDesc)))
	})
	return file_games_api_games_proto_rawDescData
}

var file_games_api_games_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_games_api_games_proto_goTypes = []any{
	(*GetGamesSummaryListRequest)(nil),  // 0: tesuji.service.v1.GetGamesSummaryListRequest
	(*GetGamesSummaryListResponse)(nil), // 1: tesuji.service.v1.GetGamesSummaryListResponse
	(*GetGameByIDRequest)(nil),          // 2: tesuji.service.v1.GetGameByIDRequest
	(*GetGameByIDResponse)(nil),         // 3: tesuji.service.v1.GetGameByIDResponse
	(*models.GameSummary)(nil),          // 4: tesuji.models.v1.GameSummary
	(*models.Game)(nil),                 // 5: tesuji.models.v1.Game
}
var file_games_api_games_proto_depIdxs = []int32{
	4, // 0: tesuji.service.v1.GetGamesSummaryListResponse.games:type_name -> tesuji.models.v1.GameSummary
	5, // 1: tesuji.service.v1.GetGameByIDResponse.game:type_name -> tesuji.models.v1.Game
	0, // 2: tesuji.service.v1.GamesService.GetGamesSummaryList:input_type -> tesuji.service.v1.GetGamesSummaryListRequest
	2, // 3: tesuji.service.v1.GamesService.GetGameByID:input_type -> tesuji.service.v1.GetGameByIDRequest
	1, // 4: tesuji.service.v1.GamesService.GetGamesSummaryList:output_type -> tesuji.service.v1.GetGamesSummaryListResponse
	3, // 5: tesuji.service.v1.GamesService.GetGameByID:output_type -> tesuji.service.v1.GetGameByIDResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_games_api_games_proto_init() }
func file_games_api_games_proto_init() {
	if File_games_api_games_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_games_api_games_proto_rawDesc), len(file_games_api_games_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_games_api_games_proto_goTypes,
		DependencyIndexes: file_games_api_games_proto_depIdxs,
		MessageInfos:      file_games_api_games_proto_msgTypes,
	}.Build()
	File_games_api_games_proto = out.File
	file_games_api_games_proto_goTypes = nil
	file_games_api_games_proto_depIdxs = nil
}
