// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/J0hnLenin/Tesuji/internal/pb/models"
)

// GameStorage is an autogenerated mock type for the GameStorage type
type GameStorage struct {
	mock.Mock
}

// GetGameByID provides a mock function with given fields: ctx, id
func (_m *GameStorage) GetGameByID(ctx context.Context, id int64) (*models.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGameByID")
	}

	var r0 *models.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetGamesSummaryList provides a mock function with given fields: ctx, page, limit
func (_m *GameStorage) GetGamesSummaryList(ctx context.Context, page uint64, limit uint64) ([]*models.GameSummary, error) {
	ret := _m.Called(ctx, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetGamesSummaryList")
	}

	var r0 []*models.GameSummary
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) ([]*models.GameSummary, error)); ok {
		return rf(ctx, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64, uint64) []*models.GameSummary); ok {
		r0 = rf(ctx, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.GameSummary)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64, uint64) error); ok {
		r1 = rf(ctx, page, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertGamesData provides a mock function with given fields: ctx, games
func (_m *GameStorage) UpsertGamesData(ctx context.Context, games []*models.Game) error {
	ret := _m.Called(ctx, games)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGamesData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Game) error); ok {
		r0 = rf(ctx, games)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newGameStorage creates a new instance of GameStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameStorage(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameStorage {
	mock := &GameStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
