// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/J0hnLenin/Tesuji/internal/pb/models"
)

// GameCache is an autogenerated mock type for the GameCache type
type GameCache struct {
	mock.Mock
}

// GetGameByID provides a mock function with given fields: ctx, id
func (_m *GameCache) GetGameByID(ctx context.Context, id int64) (*models.Game, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetGameByID")
	}

	var r0 *models.Game
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*models.Game, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *models.Game); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Game)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpsertGamesData provides a mock function with given fields: ctx, games
func (_m *GameCache) UpsertGamesData(ctx context.Context, games []*models.Game) error {
	ret := _m.Called(ctx, games)

	if len(ret) == 0 {
		panic("no return value specified for UpsertGamesData")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Game) error); ok {
		r0 = rf(ctx, games)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newGameCache creates a new instance of GameCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameCache {
	mock := &GameCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
