// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/J0hnLenin/Tesuji/internal/pb/models"
)

// GameProducer is an autogenerated mock type for the GameProducer type
type GameProducer struct {
	mock.Mock
}

// ProduceGames provides a mock function with given fields: ctx, games
func (_m *GameProducer) ProduceGames(ctx context.Context, games []*models.Game) error {
	ret := _m.Called(ctx, games)

	if len(ret) == 0 {
		panic("no return value specified for ProduceGames")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, []*models.Game) error); ok {
		r0 = rf(ctx, games)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// newGameProducer creates a new instance of GameProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewGameProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *GameProducer {
	mock := &GameProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
