name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.25.6'

      - name: Run golangci-lint
        run: |
          cd ./backend
          golangci-lint run ./...
        with:
          version: latest
          install-mode: goinstall
          args: --timeout=5m